name: Docker

on: workflow_call

permissions:
  id-token: write
  contents: read

jobs:
    ecr:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::255310614335:role/gh_actions_role_oidc
            aws-region: us-east-1

        - name: Amazon ECR Login
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
          with:
            registry-type: private

        - name: Set Docker image name
          id: set_image_name
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}
            ECR_IMAGE_URI: $REGISTRY/binance-trades-bot:$IMAGE_TAG
          run: |
            echo "ECR_IMAGE_URI="$REGISTRY/binance-trades-bot:$IMAGE_TAG >> $GITHUB_OUTPUT

        - name: Build, tag, and push docker image to Amazon ECR
          run: |
            docker build -t ${{ steps.set_image_name.outputs.ECR_IMAGE_URI }} .
            docker push ${{ steps.set_image_name.outputs.ECR_IMAGE_URI }}
