name: Deploy to lambda
on: [workflow_call]

jobs:
  deploy_zip:
    name: Deploy Lambda function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Zip code
        run: |
          mkdir dependencies
          pip install -r requirements.txt --target ./src
          cd ./src
          zip -r ../deploy.zip .
          cd ..

      - name: Deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          handler: handler.handler
          function_name: binance_trades
          zip_file: deploy.zip
