name: Python Workflow
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@1.2
    with:
      python-version: '3.10' 

  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@1.2
    with:
      python-version: '3.10' 

  deploy:
    needs: test
    uses: PedroHPAlmeida/actions-workflows-deploy-lambda/.github/workflows/deploy-lambda.yaml@1.4
    with:
      function_name: binance_trades
      handler: handler.handler 
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
