name: Python 3.8 Workflow
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  # lint:
  #   uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master

  # test:
  #   needs: lint
  #   uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  publish:
    uses: ./.github/workflows/publish.yaml

  deploy-infra:
    needs: publish
    uses: PedroHPAlmeida/actions-workflows-terraform/.github/workflows/terraform.yaml@1.0
    with:
      working-directory: ./infra
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
