name: Python 3.8 Workflow
on: [push]

jobs:
  lint:
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master
    
  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  deploy-infra:
    needs: test
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
