name: Python Workflow
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  # lint:
  #   uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master

  # test:
  #   needs: lint
  #   uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  publish:
    uses: PedroHPAlmeida/actions-workflows-terraform/.github/workflows/actions-workflows-ecr/publish-ecr.yaml@master
    with:
      image_name: binance-trades-bot
      image_tag: ${{ github.sha }}
    secrets:
      aws_role_to_assume: arn:aws:iam::255310614335:role/gh_actions_role_oidc
      aws_region: us-east-1

  deploy-infra:
    needs: publish
    uses: PedroHPAlmeida/actions-workflows-terraform/.github/workflows/terraform.yaml@1.1
    with:
      working-directory: ./infra
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
