name: Python 3.8 Workflow
on: [push]

jobs:
  lint:
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master
    
  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  build:
    needs: test
    uses: ./.github/workflows/build.yaml

  deploy-infra:
    needs: build
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit
