name: Python Workflow
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  # lint:
  #   uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@1.2
  #   with:
  #     python-version: '3.10' 

  # test:
  #   needs: lint
  #   uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@1.2
  #   with:
  #     python-version: '3.10' 

  deploy:
    needs: test
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
