name: Python 3.8 Workflow
on: [push]

jobs:
  lint:
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master

  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  # build:
  #   needs: test
  #   uses: ./.github/workflows/build.yaml

  publish:
    needs: test
    uses: ./.github/workflows/docker.yaml

  deploy-infra:
    needs: publish
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit
